2021-05-09 18:31:34,019|azureml|DEBUG|Inputs:: kwargs: {'OutputCollection': True, 'EnableMLflowTracking': True, 'snapshotProject': True, 'only_in_process_features': True, 'skip_track_logs_dir': True}, track_folders: None, deny_list: None, directories_to_watch: []
2021-05-09 18:31:34,020|azureml.history._tracking.PythonWorkingDirectory|DEBUG|Execution target type: batchai
2021-05-09 18:31:34,028|azureml.history._tracking.PythonWorkingDirectory|DEBUG|Failed to import pyspark with error: No module named 'pyspark'
2021-05-09 18:31:34,028|azureml.history._tracking.PythonWorkingDirectory.workingdir|DEBUG|Pinning working directory for filesystems: ['pyfs']
2021-05-09 18:31:34,467|azureml.core.run|DEBUG|Adding new factory <function ScriptRun._from_run_dto at 0x7fb5059039d8> for run source azureml.scriptrun
2021-05-09 18:31:34,468|azureml.core.run|DEBUG|Identity in use is not set. Falling back to using AMLToken
2021-05-09 18:31:34,468|azureml.core.run|DEBUG|Using AMLToken auth for remote run
2021-05-09 18:31:34,470|azureml.core.authentication.TokenRefresherDaemon|DEBUG|Starting daemon and triggering first instance
2021-05-09 18:31:34,478|azureml._restclient.clientbase|INFO|Created a worker pool for first use
2021-05-09 18:31:34,478|azureml.core.authentication|DEBUG|Time to expire 1814104.521057 seconds
2021-05-09 18:31:34,479|azureml._restclient.service_context|DEBUG|Created a static thread pool for ServiceContext class
2021-05-09 18:31:34,479|azureml._restclient.clientbase|DEBUG|ClientBase: Calling get with url None
2021-05-09 18:31:34,511|azureml._base_sdk_common.service_discovery|DEBUG|Found history service url in environment variable AZUREML_SERVICE_ENDPOINT, history service url: https://southcentralus.api.azureml.ms.
2021-05-09 18:31:34,511|azureml._base_sdk_common.service_discovery|DEBUG|Found history service url in environment variable AZUREML_SERVICE_ENDPOINT, history service url: https://southcentralus.api.azureml.ms.
2021-05-09 18:31:34,511|azureml._base_sdk_common.service_discovery|DEBUG|Found history service url in environment variable AZUREML_SERVICE_ENDPOINT, history service url: https://southcentralus.api.azureml.ms.
2021-05-09 18:31:34,512|azureml._base_sdk_common.service_discovery|DEBUG|Found history service url in environment variable AZUREML_SERVICE_ENDPOINT, history service url: https://southcentralus.api.azureml.ms.
2021-05-09 18:31:34,512|azureml._base_sdk_common.service_discovery|DEBUG|Found history service url in environment variable AZUREML_SERVICE_ENDPOINT, history service url: https://southcentralus.api.azureml.ms.
2021-05-09 18:31:34,512|azureml._base_sdk_common.service_discovery|DEBUG|Found history service url in environment variable AZUREML_SERVICE_ENDPOINT, history service url: https://southcentralus.api.azureml.ms.
2021-05-09 18:31:34,512|azureml._base_sdk_common.service_discovery|DEBUG|Found history service url in environment variable AZUREML_SERVICE_ENDPOINT, history service url: https://southcentralus.api.azureml.ms.
2021-05-09 18:31:34,553|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.RunClient.get_by_exp_id-async:False|DEBUG|[START]
2021-05-09 18:31:34,554|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.RunClient|DEBUG|ClientBase: Calling get_by_exp_id with url /history/v1.0/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/experimentids/{experimentId}/runs/{runId}
2021-05-09 18:31:34,620|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.RunClient.get_by_exp_id-async:False|DEBUG|[STOP]
2021-05-09 18:31:34,621|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0|DEBUG|Constructing run from dto. type: azureml.scriptrun, source: None, props: {'_azureml.ComputeTargetType': 'amlcompute', 'ContentSnapshotId': '730b20b5-6043-4e0c-b86f-3059671dffa4', 'ProcessInfoFile': 'azureml-logs/process_info.json', 'ProcessStatusFile': 'azureml-logs/process_status.json'}
2021-05-09 18:31:34,621|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunContextManager|DEBUG|Valid logs dir, setting up content loader
2021-05-09 18:31:34,622|azureml|WARNING|Could not import azureml.mlflow or azureml.contrib.mlflow mlflow APIs will not run against AzureML services.  Add azureml-mlflow as a conda dependency for the run if this behavior is desired
2021-05-09 18:31:34,622|azureml.WorkerPool|DEBUG|[START]
2021-05-09 18:31:34,622|azureml.SendRunKillSignal|DEBUG|[START]
2021-05-09 18:31:34,622|azureml.RunStatusContext|DEBUG|[START]
2021-05-09 18:31:34,622|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunContextManager.RunStatusContext|DEBUG|[START]
2021-05-09 18:31:34,623|azureml.MetricsClient|DEBUG|[START]
2021-05-09 18:31:34,623|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient|DEBUG|[START]
2021-05-09 18:31:34,623|azureml.WorkingDirectoryCM|DEBUG|[START]
2021-05-09 18:31:34,623|azureml.history._tracking.PythonWorkingDirectory.workingdir|DEBUG|[START]
2021-05-09 18:31:34,623|azureml.history._tracking.PythonWorkingDirectory|INFO|Current working dir: /mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-144286/azureml/hd_dd998e98-4a20-444c-8887-dd8601cca88b_0/mounts/workspaceblobstore/azureml/HD_dd998e98-4a20-444c-8887-dd8601cca88b_0
2021-05-09 18:31:34,623|azureml.history._tracking.PythonWorkingDirectory.workingdir|DEBUG|Calling pyfs
2021-05-09 18:31:34,623|azureml.history._tracking.PythonWorkingDirectory.workingdir|DEBUG|Storing working dir for pyfs as /mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-144286/azureml/hd_dd998e98-4a20-444c-8887-dd8601cca88b_0/mounts/workspaceblobstore/azureml/HD_dd998e98-4a20-444c-8887-dd8601cca88b_0
2021-05-09 18:31:35,260|azureml.core.run|DEBUG|Identity in use is not set. Falling back to using AMLToken
2021-05-09 18:31:35,261|azureml.core.run|DEBUG|Using AMLToken auth for remote run
2021-05-09 18:31:35,261|azureml._restclient.service_context|DEBUG|Access an existing static threadpool for ServiceContext class
2021-05-09 18:31:35,262|azureml._base_sdk_common.service_discovery|DEBUG|Found history service url in environment variable AZUREML_SERVICE_ENDPOINT, history service url: https://southcentralus.api.azureml.ms.
2021-05-09 18:31:35,270|azureml._base_sdk_common.service_discovery|DEBUG|Found history service url in environment variable AZUREML_SERVICE_ENDPOINT, history service url: https://southcentralus.api.azureml.ms.
2021-05-09 18:31:35,271|azureml._base_sdk_common.service_discovery|DEBUG|Found history service url in environment variable AZUREML_SERVICE_ENDPOINT, history service url: https://southcentralus.api.azureml.ms.
2021-05-09 18:31:35,271|azureml._base_sdk_common.service_discovery|DEBUG|Found history service url in environment variable AZUREML_SERVICE_ENDPOINT, history service url: https://southcentralus.api.azureml.ms.
2021-05-09 18:31:35,273|azureml._base_sdk_common.service_discovery|DEBUG|Found history service url in environment variable AZUREML_SERVICE_ENDPOINT, history service url: https://southcentralus.api.azureml.ms.
2021-05-09 18:31:35,274|azureml._base_sdk_common.service_discovery|DEBUG|Found history service url in environment variable AZUREML_SERVICE_ENDPOINT, history service url: https://southcentralus.api.azureml.ms.
2021-05-09 18:31:35,274|azureml._base_sdk_common.service_discovery|DEBUG|Found history service url in environment variable AZUREML_SERVICE_ENDPOINT, history service url: https://southcentralus.api.azureml.ms.
2021-05-09 18:31:35,315|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.RunClient.get_by_exp_id-async:False|DEBUG|[START]
2021-05-09 18:31:35,315|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.RunClient|DEBUG|ClientBase: Calling get_by_exp_id with url /history/v1.0/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/experimentids/{experimentId}/runs/{runId}
2021-05-09 18:31:35,381|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.RunClient.get_by_exp_id-async:False|DEBUG|[STOP]
2021-05-09 18:31:35,382|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0|DEBUG|Constructing run from dto. type: azureml.scriptrun, source: None, props: {'_azureml.ComputeTargetType': 'amlcompute', 'ContentSnapshotId': '730b20b5-6043-4e0c-b86f-3059671dffa4', 'ProcessInfoFile': 'azureml-logs/process_info.json', 'ProcessStatusFile': 'azureml-logs/process_status.json'}
2021-05-09 18:31:35,382|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunContextManager|DEBUG|Valid logs dir, setting up content loader
2021-05-09 18:31:40,571|azureml.history._tracking.PythonWorkingDirectory.workingdir|DEBUG|Calling pyfs
2021-05-09 18:31:40,572|azureml.history._tracking.PythonWorkingDirectory|INFO|Current working dir: /mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-144286/azureml/hd_dd998e98-4a20-444c-8887-dd8601cca88b_0/mounts/workspaceblobstore/azureml/HD_dd998e98-4a20-444c-8887-dd8601cca88b_0
2021-05-09 18:31:40,572|azureml.history._tracking.PythonWorkingDirectory.workingdir|DEBUG|Reverting working dir from /mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-144286/azureml/hd_dd998e98-4a20-444c-8887-dd8601cca88b_0/mounts/workspaceblobstore/azureml/HD_dd998e98-4a20-444c-8887-dd8601cca88b_0 to /mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-144286/azureml/hd_dd998e98-4a20-444c-8887-dd8601cca88b_0/mounts/workspaceblobstore/azureml/HD_dd998e98-4a20-444c-8887-dd8601cca88b_0
2021-05-09 18:31:40,572|azureml.history._tracking.PythonWorkingDirectory|INFO|Working dir is already updated /mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-144286/azureml/hd_dd998e98-4a20-444c-8887-dd8601cca88b_0/mounts/workspaceblobstore/azureml/HD_dd998e98-4a20-444c-8887-dd8601cca88b_0
2021-05-09 18:31:40,572|azureml.history._tracking.PythonWorkingDirectory.workingdir|DEBUG|[STOP]
2021-05-09 18:31:40,572|azureml.WorkingDirectoryCM|ERROR|<class '__main__.UserScriptException'>: UserScriptException:
	Message: Cannot load any data from the specified path. Make sure the path is accessible and contains data.
ScriptExecutionException was caused by StreamAccessException.
  StreamAccessException was caused by NotFoundException.
    Found no resources for the input provided: '[REDACTED]'
| session_id=l_d88d131a-b79e-4b0d-9480-dc4b0289d600
	InnerException DatasetValidationError:
	Message: Cannot load any data from the specified path. Make sure the path is accessible and contains data.
ScriptExecutionException was caused by StreamAccessException.
  StreamAccessException was caused by NotFoundException.
    Found no resources for the input provided: '[REDACTED]'
| session_id=l_d88d131a-b79e-4b0d-9480-dc4b0289d600
	InnerException None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Cannot load any data from the specified path. Make sure the path is accessible and contains data.\nScriptExecutionException was caused by StreamAccessException.\n  StreamAccessException was caused by NotFoundException.\n    Found no resources for the input provided: '[REDACTED]'\n| session_id=l_d88d131a-b79e-4b0d-9480-dc4b0289d600"
    }
}
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Cannot load any data from the specified path. Make sure the path is accessible and contains data.\nScriptExecutionException was caused by StreamAccessException.\n  StreamAccessException was caused by NotFoundException.\n    Found no resources for the input provided: '[REDACTED]'\n| session_id=l_d88d131a-b79e-4b0d-9480-dc4b0289d600"
    }
}
<traceback object at 0x7fb4f4052e08>
2021-05-09 18:31:40,572|azureml.WorkingDirectoryCM|DEBUG|[STOP]
2021-05-09 18:31:40,572|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.FlushingMetricsClient|DEBUG|[START]
2021-05-09 18:31:40,573|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient|DEBUG|Overrides: Max batch size: 50, batch cushion: 5, Interval: 1.
2021-05-09 18:31:40,573|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatch.PostMetricsBatchDaemon|DEBUG|Starting daemon and triggering first instance
2021-05-09 18:31:40,573|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient|DEBUG|Used <class 'azureml._common.async_utils.batch_task_queue.BatchTaskQueue'> for use_batch=True.
2021-05-09 18:31:40,573|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatch.WaitFlushSource:MetricsClient|DEBUG|[START]
2021-05-09 18:31:40,573|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatch.WaitFlushSource:MetricsClient|DEBUG|flush timeout 120 is different from task queue timeout 120, using flush timeout
2021-05-09 18:31:40,574|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatch.WaitFlushSource:MetricsClient|DEBUG|Waiting 120 seconds on tasks: [].
2021-05-09 18:31:40,574|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatch|DEBUG|
2021-05-09 18:31:40,574|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatch.WaitFlushSource:MetricsClient|DEBUG|[STOP]
2021-05-09 18:31:40,574|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient|DEBUG|Overrides: Max batch size: 50, batch cushion: 5, Interval: 1.
2021-05-09 18:31:40,574|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatchV2.PostMetricsBatchV2Daemon|DEBUG|Starting daemon and triggering first instance
2021-05-09 18:31:40,574|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient|DEBUG|Used <class 'azureml._common.async_utils.batch_task_queue.BatchTaskQueue'> for use_batch=True.
2021-05-09 18:31:40,575|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatchV2.WaitFlushSource:MetricsClient|DEBUG|[START]
2021-05-09 18:31:40,575|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatchV2.WaitFlushSource:MetricsClient|DEBUG|flush timeout 120 is different from task queue timeout 120, using flush timeout
2021-05-09 18:31:40,575|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatchV2.WaitFlushSource:MetricsClient|DEBUG|Waiting 120 seconds on tasks: [].
2021-05-09 18:31:40,575|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatchV2|DEBUG|
2021-05-09 18:31:40,575|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatchV2.WaitFlushSource:MetricsClient|DEBUG|[STOP]
2021-05-09 18:31:40,575|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.FlushingMetricsClient|DEBUG|[STOP]
2021-05-09 18:31:40,575|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.wait_on_ingest-async:False|DEBUG|[START]
2021-05-09 18:31:40,576|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient|DEBUG|ClientBase: Calling wait_on_ingest with url /history/v1.0/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/experiments/{experimentName}/runs/{runId}/metricsingest/wait
2021-05-09 18:31:40,635|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.wait_on_ingest-async:False|DEBUG|[STOP]
2021-05-09 18:31:40,635|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient|DEBUG|[STOP]
2021-05-09 18:31:40,636|azureml.MetricsClient|ERROR|<class '__main__.UserScriptException'>: UserScriptException:
	Message: Cannot load any data from the specified path. Make sure the path is accessible and contains data.
ScriptExecutionException was caused by StreamAccessException.
  StreamAccessException was caused by NotFoundException.
    Found no resources for the input provided: '[REDACTED]'
| session_id=l_d88d131a-b79e-4b0d-9480-dc4b0289d600
	InnerException DatasetValidationError:
	Message: Cannot load any data from the specified path. Make sure the path is accessible and contains data.
ScriptExecutionException was caused by StreamAccessException.
  StreamAccessException was caused by NotFoundException.
    Found no resources for the input provided: '[REDACTED]'
| session_id=l_d88d131a-b79e-4b0d-9480-dc4b0289d600
	InnerException None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Cannot load any data from the specified path. Make sure the path is accessible and contains data.\nScriptExecutionException was caused by StreamAccessException.\n  StreamAccessException was caused by NotFoundException.\n    Found no resources for the input provided: '[REDACTED]'\n| session_id=l_d88d131a-b79e-4b0d-9480-dc4b0289d600"
    }
}
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Cannot load any data from the specified path. Make sure the path is accessible and contains data.\nScriptExecutionException was caused by StreamAccessException.\n  StreamAccessException was caused by NotFoundException.\n    Found no resources for the input provided: '[REDACTED]'\n| session_id=l_d88d131a-b79e-4b0d-9480-dc4b0289d600"
    }
}
<traceback object at 0x7fb4f4052e08>
2021-05-09 18:31:40,636|azureml.MetricsClient|DEBUG|[STOP]
2021-05-09 18:31:40,636|azureml.RunStatusContext|ERROR|<class '__main__.UserScriptException'>: UserScriptException:
	Message: Cannot load any data from the specified path. Make sure the path is accessible and contains data.
ScriptExecutionException was caused by StreamAccessException.
  StreamAccessException was caused by NotFoundException.
    Found no resources for the input provided: '[REDACTED]'
| session_id=l_d88d131a-b79e-4b0d-9480-dc4b0289d600
	InnerException DatasetValidationError:
	Message: Cannot load any data from the specified path. Make sure the path is accessible and contains data.
ScriptExecutionException was caused by StreamAccessException.
  StreamAccessException was caused by NotFoundException.
    Found no resources for the input provided: '[REDACTED]'
| session_id=l_d88d131a-b79e-4b0d-9480-dc4b0289d600
	InnerException None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Cannot load any data from the specified path. Make sure the path is accessible and contains data.\nScriptExecutionException was caused by StreamAccessException.\n  StreamAccessException was caused by NotFoundException.\n    Found no resources for the input provided: '[REDACTED]'\n| session_id=l_d88d131a-b79e-4b0d-9480-dc4b0289d600"
    }
}
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Cannot load any data from the specified path. Make sure the path is accessible and contains data.\nScriptExecutionException was caused by StreamAccessException.\n  StreamAccessException was caused by NotFoundException.\n    Found no resources for the input provided: '[REDACTED]'\n| session_id=l_d88d131a-b79e-4b0d-9480-dc4b0289d600"
    }
}
<traceback object at 0x7fb4f4052e08>
2021-05-09 18:31:40,636|azureml.RunStatusContext|DEBUG|[STOP]
2021-05-09 18:31:40,636|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.FlushingMetricsClient|DEBUG|[START]
2021-05-09 18:31:40,637|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatch.WaitFlushSource:MetricsClient|DEBUG|[START]
2021-05-09 18:31:40,637|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatch.WaitFlushSource:MetricsClient|DEBUG|flush timeout 900.0 is different from task queue timeout 120, using flush timeout
2021-05-09 18:31:40,637|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatch.WaitFlushSource:MetricsClient|DEBUG|Waiting 900.0 seconds on tasks: [].
2021-05-09 18:31:40,637|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatch|DEBUG|
2021-05-09 18:31:40,637|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatch.WaitFlushSource:MetricsClient|DEBUG|[STOP]
2021-05-09 18:31:40,637|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatchV2.WaitFlushSource:MetricsClient|DEBUG|[START]
2021-05-09 18:31:40,637|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatchV2.WaitFlushSource:MetricsClient|DEBUG|flush timeout 900.0 is different from task queue timeout 120, using flush timeout
2021-05-09 18:31:40,637|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatchV2.WaitFlushSource:MetricsClient|DEBUG|Waiting 900.0 seconds on tasks: [].
2021-05-09 18:31:40,638|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatchV2|DEBUG|
2021-05-09 18:31:40,638|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatchV2.WaitFlushSource:MetricsClient|DEBUG|[STOP]
2021-05-09 18:31:40,638|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.FlushingMetricsClient|DEBUG|[STOP]
2021-05-09 18:31:40,638|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.wait_on_ingest-async:False|DEBUG|[START]
2021-05-09 18:31:40,638|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient|DEBUG|ClientBase: Calling wait_on_ingest with url /history/v1.0/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/experiments/{experimentName}/runs/{runId}/metricsingest/wait
2021-05-09 18:31:40,693|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.wait_on_ingest-async:False|DEBUG|[STOP]
2021-05-09 18:31:40,693|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.FlushingMetricsClient|DEBUG|[START]
2021-05-09 18:31:40,693|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient|DEBUG|Overrides: Max batch size: 50, batch cushion: 5, Interval: 1.
2021-05-09 18:31:40,694|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatch.PostMetricsBatchDaemon|DEBUG|Starting daemon and triggering first instance
2021-05-09 18:31:40,694|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient|DEBUG|Used <class 'azureml._common.async_utils.batch_task_queue.BatchTaskQueue'> for use_batch=True.
2021-05-09 18:31:40,694|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatch.WaitFlushSource:MetricsClient|DEBUG|[START]
2021-05-09 18:31:40,694|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatch.WaitFlushSource:MetricsClient|DEBUG|flush timeout 900.0 is different from task queue timeout 120, using flush timeout
2021-05-09 18:31:40,694|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatch.WaitFlushSource:MetricsClient|DEBUG|Waiting 900.0 seconds on tasks: [].
2021-05-09 18:31:40,695|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatch|DEBUG|
2021-05-09 18:31:40,695|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatch.WaitFlushSource:MetricsClient|DEBUG|[STOP]
2021-05-09 18:31:40,695|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient|DEBUG|Overrides: Max batch size: 50, batch cushion: 5, Interval: 1.
2021-05-09 18:31:40,695|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatchV2.PostMetricsBatchV2Daemon|DEBUG|Starting daemon and triggering first instance
2021-05-09 18:31:40,695|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient|DEBUG|Used <class 'azureml._common.async_utils.batch_task_queue.BatchTaskQueue'> for use_batch=True.
2021-05-09 18:31:40,695|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatchV2.WaitFlushSource:MetricsClient|DEBUG|[START]
2021-05-09 18:31:40,696|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatchV2.WaitFlushSource:MetricsClient|DEBUG|flush timeout 900.0 is different from task queue timeout 120, using flush timeout
2021-05-09 18:31:40,696|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatchV2.WaitFlushSource:MetricsClient|DEBUG|Waiting 900.0 seconds on tasks: [].
2021-05-09 18:31:40,696|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatchV2|DEBUG|
2021-05-09 18:31:40,696|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.PostMetricsBatchV2.WaitFlushSource:MetricsClient|DEBUG|[STOP]
2021-05-09 18:31:40,696|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.FlushingMetricsClient|DEBUG|[STOP]
2021-05-09 18:31:40,696|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.wait_on_ingest-async:False|DEBUG|[START]
2021-05-09 18:31:40,696|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient|DEBUG|ClientBase: Calling wait_on_ingest with url /history/v1.0/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/experiments/{experimentName}/runs/{runId}/metricsingest/wait
2021-05-09 18:31:40,755|azureml._SubmittedRun#HD_dd998e98-4a20-444c-8887-dd8601cca88b_0.RunHistoryFacade.MetricsClient.wait_on_ingest-async:False|DEBUG|[STOP]
2021-05-09 18:31:40,755|azureml.SendRunKillSignal|ERROR|<class '__main__.UserScriptException'>: UserScriptException:
	Message: Cannot load any data from the specified path. Make sure the path is accessible and contains data.
ScriptExecutionException was caused by StreamAccessException.
  StreamAccessException was caused by NotFoundException.
    Found no resources for the input provided: '[REDACTED]'
| session_id=l_d88d131a-b79e-4b0d-9480-dc4b0289d600
	InnerException DatasetValidationError:
	Message: Cannot load any data from the specified path. Make sure the path is accessible and contains data.
ScriptExecutionException was caused by StreamAccessException.
  StreamAccessException was caused by NotFoundException.
    Found no resources for the input provided: '[REDACTED]'
| session_id=l_d88d131a-b79e-4b0d-9480-dc4b0289d600
	InnerException None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Cannot load any data from the specified path. Make sure the path is accessible and contains data.\nScriptExecutionException was caused by StreamAccessException.\n  StreamAccessException was caused by NotFoundException.\n    Found no resources for the input provided: '[REDACTED]'\n| session_id=l_d88d131a-b79e-4b0d-9480-dc4b0289d600"
    }
}
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Cannot load any data from the specified path. Make sure the path is accessible and contains data.\nScriptExecutionException was caused by StreamAccessException.\n  StreamAccessException was caused by NotFoundException.\n    Found no resources for the input provided: '[REDACTED]'\n| session_id=l_d88d131a-b79e-4b0d-9480-dc4b0289d600"
    }
}
<traceback object at 0x7fb4f4052e08>
2021-05-09 18:31:40,755|azureml.SendRunKillSignal|DEBUG|[STOP]
2021-05-09 18:31:40,756|azureml.HistoryTrackingWorkerPool.WorkerPoolShutdown|DEBUG|[START]
2021-05-09 18:31:40,756|azureml.HistoryTrackingWorkerPool.WorkerPoolShutdown|DEBUG|[STOP]
2021-05-09 18:31:40,756|azureml.WorkerPool|ERROR|<class '__main__.UserScriptException'>: UserScriptException:
	Message: Cannot load any data from the specified path. Make sure the path is accessible and contains data.
ScriptExecutionException was caused by StreamAccessException.
  StreamAccessException was caused by NotFoundException.
    Found no resources for the input provided: '[REDACTED]'
| session_id=l_d88d131a-b79e-4b0d-9480-dc4b0289d600
	InnerException DatasetValidationError:
	Message: Cannot load any data from the specified path. Make sure the path is accessible and contains data.
ScriptExecutionException was caused by StreamAccessException.
  StreamAccessException was caused by NotFoundException.
    Found no resources for the input provided: '[REDACTED]'
| session_id=l_d88d131a-b79e-4b0d-9480-dc4b0289d600
	InnerException None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Cannot load any data from the specified path. Make sure the path is accessible and contains data.\nScriptExecutionException was caused by StreamAccessException.\n  StreamAccessException was caused by NotFoundException.\n    Found no resources for the input provided: '[REDACTED]'\n| session_id=l_d88d131a-b79e-4b0d-9480-dc4b0289d600"
    }
}
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Cannot load any data from the specified path. Make sure the path is accessible and contains data.\nScriptExecutionException was caused by StreamAccessException.\n  StreamAccessException was caused by NotFoundException.\n    Found no resources for the input provided: '[REDACTED]'\n| session_id=l_d88d131a-b79e-4b0d-9480-dc4b0289d600"
    }
}
<traceback object at 0x7fb4f4052e08>
2021-05-09 18:31:40,756|azureml.WorkerPool|DEBUG|[STOP]
